# Generated by Django 4.2.3 on 2023-07-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("desc", models.CharField(max_length=255)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug"),
                            ("AMELIORATION", "Amélioration"),
                            ("TACHE", "Tâche"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYEN", "Moyen"),
                            ("ELEVEE", "Elevée"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "A faire"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
