# Generated by Django 4.2.3 on 2023-07-18 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issues",
            name="assignee_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="issue_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issues",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="issue_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issues",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_issues",
                to="projects.project",
            ),
        ),
    ]
