# Generated by Django 4.2.2 on 2023-06-26 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="project_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
